<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://schmeedy.com/pdt/joomla/project/model" nsPrefix="jpm">
  <eClassifiers xsi:type="ecore:EClass" name="JoomlaExtensionProject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="project" eType="#//IProject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extensions" upperBound="-1"
        eType="#//BasicExtensionModel" containment="true" eOpposite="#//BasicExtensionModel/project"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicExtensionModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ExtensionType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manifestVersion" eType="#//ManifestVersion"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manifestPath" eType="#//IPath"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" eType="#//JoomlaExtensionProject"
        eOpposite="#//JoomlaExtensionProject/extensions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//ExtensionResource" transient="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtensionResource">
    <eOperations name="getDestinationAsFile" eType="#//File">
      <eParameters name="joomlaInstallationDir" eType="#//File"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourcePath" eType="#//IPath"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destinationPath" eType="#//IPath"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ResourceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IPath" instanceClassName="org.eclipse.core.runtime.IPath"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IProject" instanceClassName="org.eclipse.core.resources.IProject"/>
  <eClassifiers xsi:type="ecore:EDataType" name="File" instanceClassName="java.io.File"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ManifestVersion">
    <eLiterals name="UNKNOWN"/>
    <eLiterals name="ONE_FIVE" value="1" literal="1.5.0"/>
    <eLiterals name="ONE_SIX" value="2" literal="1.6.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ExtensionType">
    <eLiterals name="UNKNOWN"/>
    <eLiterals name="COMPONENT" value="1" literal="component"/>
    <eLiterals name="PLUGIN" value="2" literal="plugin"/>
    <eLiterals name="MODULE" value="3" literal="module"/>
    <eLiterals name="TEMPLATE" value="4" literal="template"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ResourceType">
    <eLiterals name="FILE"/>
    <eLiterals name="FOLDER" value="1"/>
  </eClassifiers>
</ecore:EPackage>
